apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portfolio-chart.fullname" . }}-profile-configmap
data:
  # property-like keys; each key maps to a simple value
  POSTGRESQL_HOSTNAME: "{{ .Release.Name }}-pg"
  POSTGRESQL_PORT_NUMBER: "{{ .Values.profile.db.port }}"
  POSTGRESQL_DB: "{{ .Values.profile.db.name }}"
  POSTGRESQL_URL: "postgres://postgres:$PGPASSWORD@{{ $.Release.Name }}-pg:{{ .Values.profile.db.port }}/main?sslmode=disable"
  SESSION_COOKIE: "{{ .Values.profile.oidc.SESSION_COOKIE }}"
  OIDC_CLIENT_ID: "{{ .Values.profile.oidc.OIDC_CLIENT_ID }}"
  OIDC_AUTH_URL:  "{{ .Values.profile.oidc.OIDC_AUTH_URL }}"
  OIDC_TOKEN_URL: "{{ .Values.profile.oidc.OIDC_TOKEN_URL }}"
  OIDC_USERINFO_URL:  "{{ .Values.profile.oidc.OIDC_USERINFO_URL }}"
  OIDC_CALLBACK_URL: "{{ .Values.profile.oidc.OIDC_CALLBACK_URL }}"
  OIDC_CONFIG_URL: "{{ .Values.profile.oidc.OIDC_CONFIG_URL }}"
  OIDC_ISSUER_URL: "{{ .Values.profile.oidc.OIDC_ISSUER_URL }}"
  OIDC_JWKS_URL: "{{ .Values.profile.oidc.OIDC_JWKS_URL }}"