{{ $fullName := include "portfolio-chart.fullname" . }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName}}-profile-service
  labels:
    helm.sh/chart: {{ include "portfolio-chart.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "portfolio-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: {{ $fullName}}-profile
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080