apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portfolio-chart.fullname" . }}-profile-secret
type: Opaque
data:
  POSTGRES_USER: "{{ .Values.profile.db.user | b64enc}}"
  POSTGRES_PASSWORD: "{{ .Values.profile.db.password | b64enc }}"