{{ $fullName := include "portfolio-chart.fullname" . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName}}-profile-deployment
  labels:
    app: {{ $fullName}}-profile
    helm.sh/chart: {{ include "portfolio-chart.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "portfolio-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullName}}-profile
  template:
    metadata:
      labels:
        app: {{ $fullName}}-profile
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: profile
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.profile.image.repository }}:{{ .Values.profile.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.profile.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080        
        # readinessProbe:
        #   httpGet:
        #     path: /health/readiness
        #     port: http
        env:
          - name: POSTGRESQL_HOSTNAME
            valueFrom:
              configMapKeyRef:              
                name: {{ include "portfolio-chart.fullname" . }}-profile-configmap              
                key: POSTGRESQL_HOSTNAME
          - name: POSTGRESQL_PORT_NUMBER
            valueFrom:
                configMapKeyRef:              
                  name: {{ include "portfolio-chart.fullname" . }}-profile-configmap              
                  key: POSTGRESQL_PORT_NUMBER
          - name: POSTGRESQL_DB
            valueFrom:
                configMapKeyRef:              
                  name: {{ include "portfolio-chart.fullname" . }}-profile-configmap              
                  key: POSTGRESQL_DB
          - name: SESSION_COOKIE
            valueFrom:
                configMapKeyRef:              
                  name: {{ include "portfolio-chart.fullname" . }}-profile-configmap              
                  key: SESSION_COOKIE
          - name: OIDC_CLIENT_ID
            valueFrom:
                configMapKeyRef:              
                  name: {{ include "portfolio-chart.fullname" . }}-profile-configmap              
                  key: OIDC_CLIENT_ID
          - name: OIDC_AUTH_URL
            valueFrom:
                configMapKeyRef:              
                  name: {{ include "portfolio-chart.fullname" . }}-profile-configmap              
                  key: OIDC_AUTH_URL
          - name: OIDC_TOKEN_URL
            valueFrom:
                configMapKeyRef:              
                  name: {{ include "portfolio-chart.fullname" . }}-profile-configmap              
                  key: OIDC_TOKEN_URL
          - name: OIDC_USERINFO_URL
            valueFrom:
                configMapKeyRef:              
                  name: {{ include "portfolio-chart.fullname" . }}-profile-configmap              
                  key: OIDC_USERINFO_URL
          - name: OIDC_CALLBACK_URL
            valueFrom:
                configMapKeyRef:              
                  name: {{ include "portfolio-chart.fullname" . }}-profile-configmap              
                  key: OIDC_CALLBACK_URL
          - name: OIDC_CONFIG_URL
            valueFrom:
                configMapKeyRef:              
                  name: {{ include "portfolio-chart.fullname" . }}-profile-configmap              
                  key: OIDC_CONFIG_URL
          - name: OIDC_ISSUER_URL
            valueFrom:
                configMapKeyRef:              
                  name: {{ include "portfolio-chart.fullname" . }}-profile-configmap              
                  key: OIDC_ISSUER_URL
          - name: OIDC_JWKS_URL
            valueFrom:
                configMapKeyRef:              
                  name: {{ include "portfolio-chart.fullname" . }}-profile-configmap              
                  key: OIDC_JWKS_URL
          - name: POSTGRES_USER
            valueFrom:
                secretKeyRef:              
                  name: {{ include "portfolio-chart.fullname" . }}-profile-secret
                  key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:              
                  name: {{ include "portfolio-chart.fullname" . }}-profile-secret
                  key: POSTGRES_PASSWORD
          - name: OIDC_CLIENT_SECRET
            valueFrom:
                secretKeyRef:              
                  name: {{ include "portfolio-chart.fullname" . }}-profile-secret
                  key: OIDC_CLIENT_SECRET
          