{{ $fullName := include "portfolio-chart.fullname" . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName}}-client-deployment
  labels:
    app: {{ $fullName}}-web-client
    helm.sh/chart: {{ include "portfolio-chart.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "portfolio-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullName}}-web-client
  template:
    metadata:
      labels:
        app: {{ $fullName}}-web-client
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: portfolio
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP